SHELL=/bin/bash
PATH=/bin:/usr/bin:/usr/local/bin
INC=./inc
LIB=./lib
SRC=./src
OBJ=./obj

SDLFLAGS=`sdl2-config --cflags`
SDLLIBS=`sdl2-config --libs`

CC=g++ -c -Wall -O1 -I$(INC) $(SDLFLAGS)
CL=g++ -Wall -L$(LIB)

include Makefile