INC=./inc
LIB=./lib
SRC=./src
OBJ=./obj

SDLFLAGS=`sdl2-config --cflags`
SDLLIBS=`sdl2-config --libs`

CC=g++ -c -Wall -I$(INC) $(SDLFLAGS)
CL=g++ -Wall -L$(LIB) -L /cygdrive/c/MinGW/lib -lmingw32

EXEC_EXT=.exe

include Makefile